services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: snmp-olt-zte:latest
    container_name: snmp-olt-zte
    restart: always
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_MIN_IDLE_CONNECTIONS=200
      - REDIS_POOL_SIZE=12000
      - REDIS_POOL_TIMEOUT=240
      - SNMP_HOST=192.168.20.6
      - SNMP_PORT=161
      - SNMP_COMMUNITY=public
    ports:
      - "8081:8081"